name: tangram
base: core22
adopt-info: tangram
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
    
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/webkitgtk-6.0:
    bind: $SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET/webkitgtk-6.0    
    
slots:
  tangram:
    interface: dbus
    bus: session
    name: re.sonny.Tangram

plugs:
  webkitgtk-6-gnome-2204:
    interface: content
    target: $SNAP/webkitgtk-platform
    default-provider: webkitgtk-6-gnome-2204


apps:
  tangram:
    command: usr/bin/re.sonny.Tangram
    extensions: [gnome]
    common-id: re.sonny.Tangram
    environment:
      GI_TYPELIB_PATH: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/gjs/girepository-1.0:$SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0


parts:
  tangram:
    source: https://github.com/sonnyp/Tangram.git
    source-tag: 'v3.0'
    plugin: meson
    parse-info: [ usr/share/metainfo/re.sonny.Tangram.metainfo.xml ]
    build-environment:
      - PKG_CONFIG_PATH: /snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:$PKG_CONFIG_PATH
      - PATH: /snap/webkitgtk-6-gnome-2204-sdk/current/usr/bin:$PATH
      - XDG_DATA_DIRS: /snap/webkitgtk-6-gnome-2204-sdk/current/usr/share:$XDG_DATA_DIRS
      - GI_TYPELIB_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:/snap/gnome-42-2204-sdk/current/usr/lib/girepository-1.0:/snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0
      - LD_LIBRARY_PATH: /snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib:/snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/webkitgtk-6.0:/snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$LD_LIBRARY_PATH
    meson-parameters:
      - --prefix=/snap/tangram/current/usr
    build-packages:
      - libgjs-dev
    build-snaps:
      - webkitgtk-6-gnome-2204-sdk/latest/edge  
    organize:
      snap/tangram/current: .
  gst:
    plugin: nil
    stage-packages: 
      - gir1.2-gstreamer-1.0
    prime:
      - usr/lib/x86_64-linux-gnu/girepository-1.0/Gst-1.0.typelib
      - usr/lib/x86_64-linux-gnu/girepository-1.0/GstBase-1.0.typelib
      - usr/lib/x86_64-linux-gnu/girepository-1.0/GstCheck-1.0.typelib
      - usr/lib/x86_64-linux-gnu/girepository-1.0/GstController-1.0.typelib
      - usr/lib/x86_64-linux-gnu/girepository-1.0/GstNet-1.0.typelib
    
